"use server";

import { revalidatePath } from "next/cache";

import { prisma } from "@/lib/prisma";
import { type AdminResult, parseForm, runAction } from "@/lib/admin/form";
import { audit } from "@/lib/admin/audit";
import { requireAdminUser } from "@/lib/admin/guard";
import {
  discountGrantSchema,
  prescriptionSchema,
  purchaseSchema,
} from "@/lib/admin/schemas";

/**
 * Admin CRUD for the patient records that My Profile reads: prescriptions,
 * online purchases and discount grants.
 *
 * These are entered by staff rather than generated by the client's own
 * actions, so they live behind the admin console. Everything is audited —
 * they are the patient's record, and a change to one should be traceable.
 */

/** Blank date input means "now"; anything else is a YYYY-MM-DD day. */
function dateOrNow(value?: string): Date {
  if (!value) return new Date();
  const at = new Date(`${value}T00:00:00.000Z`);
  return Number.isNaN(at.getTime()) ? new Date() : at;
}

function dateOrNull(value?: string): Date | null {
  if (!value) return null;
  const at = new Date(`${value}T00:00:00.000Z`);
  return Number.isNaN(at.getTime()) ? null : at;
}

/** The patient's own page is cached per-path; a new record must show up. */
function revalidatePatient() {
  revalidatePath("/patient/profile");
}

/* ------------------------------ Prescriptions ---------------------------- */

export async function savePrescription(
  id: string | null,
  formData: FormData
): Promise<AdminResult> {
  return runAction("savePrescription", async () => {
    const user = await requireAdminUser();
    const parsed = parseForm(prescriptionSchema, formData);
    if (!parsed.ok) return parsed.result;

    const d = parsed.data;
    const data = {
      userId: d.userId,
      doctorId: d.doctorId || null,
      title: d.title,
      notes: d.notes || null,
      fileUrl: d.fileUrl,
      issuedAt: dateOrNow(d.issuedAt),
    };

    const before = id
      ? await prisma.prescription.findUnique({ where: { id } })
      : null;
    const row = id
      ? await prisma.prescription.update({ where: { id }, data })
      : await prisma.prescription.create({ data });

    await audit({
      userId: user.id,
      action: id ? "update" : "create",
      entity: "Prescription",
      entityId: row.id,
      before,
      after: row,
    });

    revalidatePatient();
    revalidatePath("/admin/prescriptions");
    return { ok: true, id: row.id };
  });
}

export async function deletePrescription(id: string): Promise<AdminResult> {
  return runAction("deletePrescription", async () => {
    const user = await requireAdminUser();
    const before = await prisma.prescription.findUnique({ where: { id } });
    await prisma.prescription.delete({ where: { id } });
    await audit({
      userId: user.id,
      action: "delete",
      entity: "Prescription",
      entityId: id,
      before,
    });
    revalidatePatient();
    revalidatePath("/admin/prescriptions");
    return { ok: true };
  });
}

/* -------------------------------- Purchases ------------------------------ */

export async function savePurchase(
  id: string | null,
  formData: FormData
): Promise<AdminResult> {
  return runAction("savePurchase", async () => {
    const user = await requireAdminUser();
    const parsed = parseForm(purchaseSchema, formData);
    if (!parsed.ok) return parsed.result;

    const d = parsed.data;
    const data = {
      userId: d.userId,
      itemName: d.itemName,
      quantity: d.quantity,
      status: d.status,
      amountInr: d.amountInr ?? null,
      orderedAt: dateOrNow(d.orderedAt),
    };

    const before = id ? await prisma.purchase.findUnique({ where: { id } }) : null;
    const row = id
      ? await prisma.purchase.update({ where: { id }, data })
      : await prisma.purchase.create({ data });

    await audit({
      userId: user.id,
      action: id ? "update" : "create",
      entity: "Purchase",
      entityId: row.id,
      before,
      after: row,
    });

    revalidatePatient();
    revalidatePath("/admin/purchases");
    return { ok: true, id: row.id };
  });
}

export async function deletePurchase(id: string): Promise<AdminResult> {
  return runAction("deletePurchase", async () => {
    const user = await requireAdminUser();
    const before = await prisma.purchase.findUnique({ where: { id } });
    await prisma.purchase.delete({ where: { id } });
    await audit({
      userId: user.id,
      action: "delete",
      entity: "Purchase",
      entityId: id,
      before,
    });
    revalidatePatient();
    revalidatePath("/admin/purchases");
    return { ok: true };
  });
}

/* ----------------------------- Discount grants --------------------------- */

export async function saveDiscountGrant(
  id: string | null,
  formData: FormData
): Promise<AdminResult> {
  return runAction("saveDiscountGrant", async () => {
    const user = await requireAdminUser();
    const parsed = parseForm(discountGrantSchema, formData);
    if (!parsed.ok) return parsed.result;

    const d = parsed.data;
    const before = id
      ? await prisma.discountGrant.findUnique({ where: { id } })
      : null;

    // Ticking "used" stamps the redemption once and leaves the original
    // timestamp alone on later edits; unticking clears it.
    const usedAt = d.markUsed ? before?.usedAt ?? new Date() : null;

    const data = {
      userId: d.userId,
      code: d.code,
      description: d.description,
      percentOff: d.percentOff ?? null,
      amountOffInr: d.amountOffInr ?? null,
      expiresAt: dateOrNull(d.expiresAt),
      usedAt,
    };

    const row = id
      ? await prisma.discountGrant.update({ where: { id }, data })
      : await prisma.discountGrant.create({ data });

    await audit({
      userId: user.id,
      action: id ? "update" : "create",
      entity: "DiscountGrant",
      entityId: row.id,
      before,
      after: row,
    });

    revalidatePatient();
    revalidatePath("/admin/discounts");
    return { ok: true, id: row.id };
  });
}

export async function deleteDiscountGrant(id: string): Promise<AdminResult> {
  return runAction("deleteDiscountGrant", async () => {
    const user = await requireAdminUser();
    const before = await prisma.discountGrant.findUnique({ where: { id } });
    await prisma.discountGrant.delete({ where: { id } });
    await audit({
      userId: user.id,
      action: "delete",
      entity: "DiscountGrant",
      entityId: id,
      before,
    });
    revalidatePatient();
    revalidatePath("/admin/discounts");
    return { ok: true };
  });
}
