/**
 * Generates the theme override layer in globals.css.
 *
 *   npx tsx prisma/gen-theme-overrides.ts            # write
 *   npx tsx prisma/gen-theme-overrides.ts --check    # fail if out of date
 *
 * ── The problem this exists to solve ─────────────────────────────────────
 * The client site is written in LITERAL dark-theme colours — `text-teal-300`,
 * `text-white/70`, `bg-white/[0.04]`, `hover:text-brand-200`. There are 132
 * distinct ones across roughly 1,300 uses, every one chosen to sit on navy.
 *
 * The first attempt at a light theme flipped the TOKENS underneath them and
 * left the literals alone, which produced exactly what you would expect: pale
 * teal type on a white page, an account menu whose hover was a wash of light
 * blue with near-white text on it, and a promotional banner that read as an
 * empty box. The tokens moved; the thousand-odd colours painted on top of
 * them did not.
 *
 * Converting 1,300 call sites by hand is neither reliable nor reviewable, and
 * it would have to be done again for every new component. So the literal
 * itself becomes the hook: each one gets a rule that repaints it from a token,
 * and the tokens are what a theme changes.
 *
 * ── Why it is generated rather than hand-written ─────────────────────────
 * A hand-written list goes stale the first time somebody adds
 * `text-teal-400` to a new component, and it goes stale SILENTLY — the
 * component simply becomes unreadable on three of the four themes and nobody
 * finds out until a screenshot arrives. This scans the source, so the list is
 * whatever the source actually uses, and `--check` fails the build when the
 * two disagree.
 *
 * ── What is deliberately untouched ───────────────────────────────────────
 * The default theme. `midnight` is the site as it has always looked, and not
 * one of these rules applies to it — they are all scoped to
 * `[data-theme]:not([data-theme="midnight"])`. A theme system that changes
 * the default while adding options to it is a redesign wearing a smaller hat.
 *
 * The doctor portal and the admin console are skipped for the opposite
 * reason: they are permanently light, built on literal light classes, and
 * carry `.theme-light` explicitly.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, sep } from "node:path";

const CSS_PATH = "src/app/globals.css";
const START = "/* THEME-OVERRIDES:START — generated by prisma/gen-theme-overrides.ts */";
const END = "/* THEME-OVERRIDES:END */";

/* ------------------------------- Scanning -------------------------------- */

const ROOTS = ["src/app", "src/components"];

/** Always-light surfaces. They opt out with `.theme-light` and stay put. */
function skip(path: string): boolean {
  return (
    path.includes(`app${sep}admin`) ||
    path.includes(`${sep}portal${sep}`) ||
    path.includes(`components${sep}admin${sep}`) ||
    path.includes(`components${sep}doctor${sep}`)
  );
}

function files(dir: string, out: string[] = []): string[] {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) files(p, out);
    else if (e.name.endsWith(".tsx") && !skip(p)) out.push(p);
  }
  return out;
}

/**
 * Every class token in a file.
 *
 * Split out of string literals rather than matched with one big regex,
 * because a Tailwind class carrying an arbitrary value — `bg-white/[0.04]` —
 * has brackets and a dot in it and a regex that copes with all of those
 * reliably is a regex nobody can read.
 */
function classTokens(src: string): string[] {
  const out: string[] = [];
  for (const m of src.matchAll(/["'`]([^"'`]{2,400})["'`]/g)) {
    for (const t of m[1].split(/\s+/)) {
      if (t.length > 2 && t.length < 60) out.push(t);
    }
  }
  return out;
}

/* ------------------------- Literal -> token rules ------------------------ */

/** Splits `hover:text-white/70` into its parts. */
interface Parsed {
  variant: string;
  prop: "text" | "bg" | "border" | "ring" | "divide" | "from" | "to" | "via";
  hue: string;
  step: string;
  /** 0-100. 100 when no modifier. */
  alpha: number;
}

const HUE_TOKEN: Record<string, string> = {
  white: "--ink",
  // Slate is the LIGHT-surface family: this site paints its white cards with
  // bg-white + text-slate-900 + border-slate-200. Those are just as
  // theme-dependent as the dark ones, in the opposite direction, and leaving
  // them out is what turned every white card near-black on the light themes.
  slate: "--ink",
  brand: "--accent-text",
  teal: "--highlight-text",
  amber: "--warn-text",
  rose: "--danger-text",
  violet: "--violet-text",
  emerald: "--emerald-text",
  sky: "--accent-text",
  indigo: "--violet-text",
};

/** Fills and borders use a wash base rather than a text colour. */
const HUE_WASH: Record<string, string> = {
  white: "--wash",
  slate: "--wash",
  brand: "--accent-wash",
  teal: "--highlight-wash",
  amber: "--warn-wash",
  rose: "--danger-wash",
  violet: "--violet-wash",
  emerald: "--emerald-wash",
  sky: "--accent-wash",
  indigo: "--violet-wash",
};

/** Text steps that only work on a dark ground. 400+ is legible on both. */
const PALE_TEXT_STEPS = new Set(["50", "100", "200", "300"]);
/** Fill steps used as a translucent tint. */
const TINT_STEPS = new Set(["300", "400", "500", "600"]);

/**
 * Slate steps used as READING text on a white card. 700-900 is body copy,
 * 400-600 is the quiet register.
 */
const SLATE_INK_STEPS = new Set(["700", "800", "900", "950"]);
const SLATE_SOFT_STEPS = new Set(["500", "600"]);
const SLATE_MUTED_STEPS = new Set(["300", "400"]);
/** Slate steps used as a card or a faint fill. */
const SLATE_FILL_STEPS = new Set(["50", "100", "200"]);
/** Slate steps used as a hairline. */
const SLATE_EDGE_STEPS = new Set(["100", "200", "300"]);

function parse(token: string): Parsed | null {
  const m =
    /^(?:([a-z-]+(?:\[[^\]]*\])?):)?(text|bg|border|ring|divide|from|to|via)-([a-z]+)(?:-(\d{2,3}))?(?:\/(\[[\d.]+%?\]|\d+))?$/.exec(
      token
    );
  if (!m) return null;
  const [, variant, prop, hue, step, mod] = m;
  if (!(hue in HUE_TOKEN)) return null;

  let alpha = 100;
  if (mod) {
    const raw = mod.replace(/[[\]%]/g, "");
    const n = Number(raw);
    if (!Number.isFinite(n)) return null;
    // Tailwind accepts both `/10` (percent) and `/[0.04]` (fraction).
    alpha = mod.startsWith("[") && n <= 1 ? n * 100 : n;
  }

  return {
    variant: variant ?? "",
    prop: prop as Parsed["prop"],
    hue,
    step: step ?? "",
    alpha,
  };
}

/**
 * Does this literal have to be repainted for a theme to work?
 *
 * -- Two families, and missing the second one is what broke it -----------
 * The obvious family is the DARK-ONLY literals: `text-white`, `text-teal-300`,
 * `bg-white/[0.04]`. Every one was chosen to sit on navy and every one has to
 * change on a light theme. That family was handled.
 *
 * The family that was missed is the LIGHT-ONLY one. This site paints a real
 * white card as `bg-white text-slate-900 border-slate-200` — an aftercare
 * sheet, a booking panel, the assistant. Those are equally theme-dependent,
 * and on the contrast theme a white card with slate text is exactly as wrong
 * as a navy card with white text is on daylight.
 *
 * Worse, `bg-white` was being caught by the dark family (`hue === "white"`)
 * and repainted with `--wash`, which on daylight is #0f172a. So every opaque
 * white card on the site turned near-black while its slate text stayed dark.
 * That is the reported "text is invisible" bug, and it is separate from the
 * hardcoded navy sections.
 */
function shouldRepaint(p: Parsed): boolean {
  if (p.hue === "white") return true;

  if (p.hue === "slate") {
    if (p.prop === "text") {
      return (
        SLATE_INK_STEPS.has(p.step) ||
        SLATE_SOFT_STEPS.has(p.step) ||
        SLATE_MUTED_STEPS.has(p.step)
      );
    }
    if (p.prop === "bg") return p.alpha >= 100 && SLATE_FILL_STEPS.has(p.step);
    if (p.prop === "border" || p.prop === "ring" || p.prop === "divide") {
      return SLATE_EDGE_STEPS.has(p.step);
    }
    return false;
  }

  if (p.prop === "text" || p.prop === "from" || p.prop === "to" || p.prop === "via") {
    return PALE_TEXT_STEPS.has(p.step);
  }
  // A tinted fill or edge is only dark-only when it is translucent: a solid
  // bg-brand-600 button is a brand button on any ground and must not be
  // repainted.
  return p.alpha < 100 && TINT_STEPS.has(p.step);
}

const CSS_PROP: Record<Parsed["prop"], string> = {
  text: "color",
  bg: "background-color",
  border: "border-color",
  ring: "--tw-ring-color",
  divide: "border-color",
  from: "--tw-gradient-from",
  to: "--tw-gradient-to",
  via: "--tw-gradient-via",
};

function value(p: Parsed): string {
  // ── An opaque white is a CARD, not a wash ───────────────────────────
  // `bg-white/[0.04]` is a translucent lift on navy and belongs to --wash.
  // Plain `bg-white` is an actual white panel and belongs to --sheet. They
  // were treated as the same thing, so on daylight every white card was
  // painted #0f172a and every bit of slate text on it disappeared.
  if (p.prop === "bg" && p.alpha >= 100) {
    if (p.hue === "white") return "var(--sheet)";
    if (p.hue === "slate") return "var(--tint)";
  }

  // Slate text keeps its three-step hierarchy rather than flattening to one
  // colour: body, quiet, and quieter still are three different jobs.
  if (p.prop === "text" && p.hue === "slate") {
    if (SLATE_SOFT_STEPS.has(p.step)) {
      return "color-mix(in srgb, var(--ink) var(--ink-soft-mix), transparent)";
    }
    if (SLATE_MUTED_STEPS.has(p.step)) {
      return "color-mix(in srgb, var(--ink) var(--ink-muted-mix), transparent)";
    }
    return "var(--ink)";
  }

  // Every slate edge is one hairline. The 100/200/300 distinction is a
  // rounding error on a light card and nothing at all on a dark one.
  if (
    p.hue === "slate" &&
    (p.prop === "border" || p.prop === "ring" || p.prop === "divide")
  ) {
    return "var(--hairline)";
  }

  const token = p.prop === "text" ? HUE_TOKEN[p.hue] : HUE_WASH[p.hue];
  if (p.alpha >= 100) return `var(${token})`;
  // color-mix rather than an rgba() the token cannot express: the token is a
  // hex the theme sets, and there is no way to interpolate an alpha into it.
  return `color-mix(in srgb, var(${token}) ${round(p.alpha)}%, transparent)`;
}

const round = (n: number) => Math.round(n * 100) / 100;

/**
 * The two subtrees a themed rule must never enter.
 *
 * `.on-dark` marks a surface that is DELIBERATELY dark on every theme — a hero
 * over a photograph, a modal scrim, a brand gradient. Repainting the text
 * inside one to var(--ink) is what put dark type on the dark Gold Collar card.
 *
 * `.pro-surface` marks the professional console — the doctor portal, the admin
 * screens, the join flow. Several hundred literal light classes that a theme
 * must not touch: without this the contrast theme would invert forty clinical
 * screens mid-consultation.
 *
 * It is deliberately NOT `.theme-light`, which was doing two different jobs
 * under one name. The console uses it to lock itself light forever; client
 * pages like a treatment or a product used it to put a light island on the
 * dark default. Excluding both left whole client pages white on every theme,
 * which is its own version of "the theme did not apply".
 *
 * Both list the element AND its descendants, because a card's own background
 * and the text inside it are both wrong to repaint.
 *
 * The complex selector inside :not() is Selectors Level 4 and is supported in
 * every browser this app targets. It contributes the specificity of its most
 * specific argument, (0,1,0) here, which only strengthens rules that already
 * had to beat a utility.
 */
const EXCLUDE = ":not(.on-dark, .on-dark *):not(.pro-surface, .pro-surface *)";

/** `.hover\:text-white\/70:hover` — the class name, escaped, plus its state. */
function selector(token: string, p: Parsed): string {
  const escaped = token.replace(/([.:/[\]%])/g, "\\$1");
  const state = p.variant
    ? p.variant.replace(/^group-/, "").replace(/^peer-/, "")
    : "";

  let sel = `.${escaped}${EXCLUDE}`;
  if (p.variant.startsWith("group-")) return `.group:${state} ${sel}`;
  if (p.variant.startsWith("peer-")) return `.peer:${state} ~ ${sel}`;
  if (state && ["hover", "focus", "active", "disabled"].includes(state)) {
    sel += `:${state}`;
  } else if (state && state.startsWith("focus-visible")) {
    sel += ":focus-visible";
  } else if (state) {
    // A responsive or arbitrary variant. Left alone rather than guessed at:
    // a wrong media query is worse than an unthemed colour, and --check
    // reports it so it can be handled deliberately.
    return "";
  }
  if (p.prop === "divide") return `${sel} > * + *`;
  return sel;
}

/* -------------------------------- Build ---------------------------------- */

function build(): { css: string; count: number; skipped: string[] } {
  const seen = new Set<string>();
  for (const f of ROOTS.flatMap((r) => files(r))) {
    for (const t of classTokens(readFileSync(f, "utf8"))) seen.add(t);
  }

  const rules: string[] = [];
  const skipped: string[] = [];
  const done = new Set<string>();

  for (const token of [...seen].sort()) {
    const p = parse(token);
    if (!p || !shouldRepaint(p)) continue;

    const sel = selector(token, p);
    if (!sel) {
      skipped.push(token);
      continue;
    }
    if (done.has(sel)) continue;
    done.add(sel);

    rules.push(`${sel} { ${CSS_PROP[p.prop]}: ${value(p)}; }`);
  }

  const scope = ':root[data-theme]:not([data-theme="midnight"])';
  const body = rules.map((r) => `${scope} ${r}`).join("\n");

  const css = `${START}
/*
 * Every dark-only colour literal the client surface uses, repainted from a
 * token. DO NOT EDIT BY HAND — run:
 *
 *   npx tsx prisma/gen-theme-overrides.ts
 *
 * Scoped away from the default theme on purpose: \`midnight\` is the site as
 * it has always looked and not one of these rules touches it.
 *
 * ${rules.length} rules, generated from the source.
 */
${body}
${END}`;

  return { css, count: rules.length, skipped };
}

/* --------------------------------- Main ---------------------------------- */

const { css, count, skipped } = build();
const current = readFileSync(CSS_PATH, "utf8");

const startAt = current.indexOf(START);
const endAt = current.indexOf(END);
const existing =
  startAt > -1 && endAt > -1 ? current.slice(startAt, endAt + END.length) : "";

if (process.argv.includes("--check")) {
  if (existing === css) {
    console.log(`Theme overrides are up to date (${count} rules).`);
    if (skipped.length) {
      console.log(`Not themed (unusual variants): ${skipped.join(", ")}`);
    }
    process.exit(0);
  }
  console.error(
    "Theme overrides are STALE. A dark-only colour has been added or removed\n" +
      "since they were generated, which means it renders unthemed — invisible\n" +
      "on at least one theme. Run:\n\n  npx tsx prisma/gen-theme-overrides.ts\n"
  );
  process.exit(1);
}

const next =
  startAt > -1 && endAt > -1
    ? current.slice(0, startAt) + css + current.slice(endAt + END.length)
    : `${current.trimEnd()}\n\n${css}\n`;

writeFileSync(CSS_PATH, next);
console.log(`Wrote ${count} theme override rules to ${CSS_PATH}.`);
if (skipped.length) {
  console.log(`\nNot themed (unusual variants, handle by hand if needed):`);
  skipped.forEach((s) => console.log(`  ${s}`));
}
